disabled_rules:
  - trailing_comma
  - trailing_whitespace

opt_in_rules:
  - empty_count
  - toggle_bool
  - empty_string
  - fatal_error_message
  - first_where
  - modifier_order
  - private_action
  - private_outlet
  - overridden_super_call
  - force_try
  - force_unwrapping
  - function_body_length
  - file_length

line_length:
  warning: 150
  error: 200
  ignores_function_declarations: true
  ignores_comments: true
  ignores_urls: true
function_body_length:
  warning: 300
  error: 500
function_parameter_count:
  warning: 6
  error: 8
type_body_length:
  warning: 300
  error: 500
file_length:
  warning: 1000
  error: 1500
  ignore_comment_only_lines: true
